version: '3.4'
services:
  api:
    build: .

    ports:
      - 5000:5000
    command: ["python", "run.py"]
    volumes:
      - .:/api

    depends_on:
      - database
  migration:
    build: .
    command: >
      sh -c "python manage.py db init &&
            python manage.py db migrate &&
            python manage.py db upgrade"
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flower_shop
      PGDATA: /var/lib/postgresql/data
    networks:
      - default
    restart: always