version: '3.4'
services:
  api:
    build: .
    ports:
      - 5000:5000
    command: ["flask", "run", "--host", "0.0.0.0"]
    volumes:
      - .:/app
    restart: always

    depends_on:
      - database
  migration:
    build: .
    command: >
      sh -c "python manage.py db migrate &&
            python manage.py db upgrade"
    depends_on:
      - api
      - database
  database:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flower_shop
      PGDATA: /var/lib/postgresql/data
    restart: always